/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BgButton {
        "color": string;
        "disabled": boolean;
        "label": string;
        "styleclass": string;
    }
    interface BgInput {
        "name": string;
        "placeholder": string;
        "styleclass": string;
        "value": string;
    }
    interface StCard {
    }
    interface StCardContent {
    }
    interface StCardHeader {
    }
    interface TsCardBottom {
    }
}
export interface BgButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBgButtonElement;
}
export interface BgInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBgInputElement;
}
declare global {
    interface HTMLBgButtonElement extends Components.BgButton, HTMLStencilElement {
    }
    var HTMLBgButtonElement: {
        prototype: HTMLBgButtonElement;
        new (): HTMLBgButtonElement;
    };
    interface HTMLBgInputElement extends Components.BgInput, HTMLStencilElement {
    }
    var HTMLBgInputElement: {
        prototype: HTMLBgInputElement;
        new (): HTMLBgInputElement;
    };
    interface HTMLStCardElement extends Components.StCard, HTMLStencilElement {
    }
    var HTMLStCardElement: {
        prototype: HTMLStCardElement;
        new (): HTMLStCardElement;
    };
    interface HTMLStCardContentElement extends Components.StCardContent, HTMLStencilElement {
    }
    var HTMLStCardContentElement: {
        prototype: HTMLStCardContentElement;
        new (): HTMLStCardContentElement;
    };
    interface HTMLStCardHeaderElement extends Components.StCardHeader, HTMLStencilElement {
    }
    var HTMLStCardHeaderElement: {
        prototype: HTMLStCardHeaderElement;
        new (): HTMLStCardHeaderElement;
    };
    interface HTMLTsCardBottomElement extends Components.TsCardBottom, HTMLStencilElement {
    }
    var HTMLTsCardBottomElement: {
        prototype: HTMLTsCardBottomElement;
        new (): HTMLTsCardBottomElement;
    };
    interface HTMLElementTagNameMap {
        "bg-button": HTMLBgButtonElement;
        "bg-input": HTMLBgInputElement;
        "st-card": HTMLStCardElement;
        "st-card-content": HTMLStCardContentElement;
        "st-card-header": HTMLStCardHeaderElement;
        "ts-card-bottom": HTMLTsCardBottomElement;
    }
}
declare namespace LocalJSX {
    interface BgButton {
        "color"?: string;
        "disabled"?: boolean;
        "label"?: string;
        "onOnClick"?: (event: BgButtonCustomEvent<boolean>) => void;
        "styleclass"?: string;
    }
    interface BgInput {
        "name"?: string;
        "onInputChange"?: (event: BgInputCustomEvent<string>) => void;
        "placeholder"?: string;
        "styleclass"?: string;
        "value"?: string;
    }
    interface StCard {
    }
    interface StCardContent {
    }
    interface StCardHeader {
    }
    interface TsCardBottom {
    }
    interface IntrinsicElements {
        "bg-button": BgButton;
        "bg-input": BgInput;
        "st-card": StCard;
        "st-card-content": StCardContent;
        "st-card-header": StCardHeader;
        "ts-card-bottom": TsCardBottom;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bg-button": LocalJSX.BgButton & JSXBase.HTMLAttributes<HTMLBgButtonElement>;
            "bg-input": LocalJSX.BgInput & JSXBase.HTMLAttributes<HTMLBgInputElement>;
            "st-card": LocalJSX.StCard & JSXBase.HTMLAttributes<HTMLStCardElement>;
            "st-card-content": LocalJSX.StCardContent & JSXBase.HTMLAttributes<HTMLStCardContentElement>;
            "st-card-header": LocalJSX.StCardHeader & JSXBase.HTMLAttributes<HTMLStCardHeaderElement>;
            "ts-card-bottom": LocalJSX.TsCardBottom & JSXBase.HTMLAttributes<HTMLTsCardBottomElement>;
        }
    }
}
